REPO_NAME=$1;
IMAGE_TAG=$2;
IMAGE_NAME=$3;

sudo docker pull $REPO_NAME:$IMAGE_TAG
sudo docker stop $BACKEND
sudo docker rm $BACKEND
sudo docker run --name=$BACKEND --network $CSGOED_NETWORK -d -e PAGE_URL=$PAGE_URL -e DOMAIN_NAME=$DOMAIN_NAME -e DASHBOARD_URL=$DASHBOARD_URL -e MAILGUN_API_KEY=$MAILGUN_API_KEY -e MAILGUN_DOMAIN=$MAILGUN_DOMAIN -e STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY -e STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY -e MONGODB_URI=$MONGODB_URI -e MAILGUN_HOST=$MAILGUN_HOST kamilwronka7/csgoed-backend  